name: nook_lounge_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  cloud_firestore: ^6.0.2
  cloud_functions: ^6.0.2
  firebase_auth: ^6.0.2
  firebase_core: ^4.4.0
  firebase_storage: ^13.0.2
  firebase_messaging: ^16.0.2
  freezed_annotation: ^3.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.5
  google_sign_in: ^7.2.0
  image_picker: ^1.2.0
  image: ^4.5.4
  intl: ^0.20.2
  sign_in_with_apple: ^7.0.1
  flutter_svg: ^2.2.3

dev_dependencies:
  build_runner: ^2.7.0
  freezed: ^3.2.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/json/
    - assets/images/
    - assets/icon/
  fonts:
    - family: NPS
      fonts:
        - asset: assets/fonts/NPSfont_regular.ttf
          weight: 400
        - asset: assets/fonts/NPSfont_bold.ttf
          weight: 700
        - asset: assets/fonts/NPSfont_extrabold.ttf
          weight: 800
